/** @type {import('tailwindcss').Config}*/
const config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],

  theme: {
    extend: {
        scale: {
          175: '1.75',
          200: '2',
      },
      backgroundImage: {
          parchment: "url(../ui/parchment.jpg)"
      },
      colors: {
        foundry: {
          "button-background": "rgba(255, 255, 240, 0.8)",
          "text-light-highlight": "var(--color-text-light-highlight)",
          "text-light-heading": "var(--color-text-light-heading)",
          "text-light-primary": "var(--color-text-light-primary)",
          "text-dark-primary": "var(--color-text-dark-primary)",
          "text-dark-secondary": "var(--color-text-dark-secondary)",
          "text-dark-header": "var(--color-text-dark-header)",
          "text-dark-inactive": "var(--color-text-dark-inactive)",
          "text-hyperlink": "var(--color-text-hyperlink)",
          "text-light-0": "var(--color-text-light-0)",
          "text-light-1": "var(--color-text-light-1)",
          "text-light-2": "var(--color-text-light-2)",
          "text-light-3": "var(--color-text-light-3)",
          "text-light-4": "var(--color-text-light-4)",
          "text-light-5": "var(--color-text-light-5)",
          "text-light-6": "var(--color-text-light-6)",
          "text-light-7": "var(--color-text-light-7)",
          "text-dark-1": "var(--color-text-dark-1)",
          "text-dark-2": "var(--color-text-dark-2)",
          "text-dark-3": "var(--color-text-dark-3)",
          "text-dark-4": "var(--color-text-dark-4)",
          "text-dark-5": "var(--color-text-dark-5)",
          "text-dark-6": "var(--color-text-dark-6)",
          "border-light-1": "var(--color-border-light-1)",
          "border-light-2": "var(--color-border-light-2)",
          "border-dark-1": "var(--color-border-dark-1)",
          "border-dark-2": "var(--color-border-dark-2)",
          "border-dark-3": "var(--color-border-dark-3)",
          "border-dark-4": "var(--color-border-dark-4)",
          "border-dark-5": "var(--color-border-dark-5)",
          "shadow-primary": "var(--color-shadow-primary)",
          "shadow-highlight": "var(--color-shadow-highlight)",
          "shadow-dark": "var(--color-shadow-dark)",
          "underline-inactive": "var(--color-underline-inactive)",
          "underline-active": "var(--color-underline-active)",
          "underline-header": "var(--color-underline-header)",
          "border-light-highlight": "var(--color-border-light-highlight)",
          "border-light-primary": "var(--color-border-light-primary)",
          "border-light-secondary": "var(--color-border-light-secondary)",
          "border-light-tertiary": "var(--color-border-light-tertiary)",
          "border-dark": "var(--color-border-dark)",
          "border-dark-primary": "var(--color-border-dark-primary)",
          "border-dark-secondary": "var(--color-border-dark-secondary)",
          "border-dark-tertiary": "var(--color-border-dark-tertiary)",
          "border-highlight": "var(--color-border-highlight)",
          "border-highlight-alt": "var(--color-border-highlight-alt)",
          "bg-btn-minor-inactive": "var(--color-bg-btn-minor-inactive)",
          "bg-btn-minor-active": "var(--color-bg-btn-minor-active)",
          "bg-option": "var(--color-bg-option)",
          "checkbox-checked": "var(--color-checkbox-checked)",
          "ownership-none": "var(--color-ownership-none)",
          "ownership-observer": "var(--color-ownership-observer)",
          "ownership-owner": "var(--color-ownership-owner)",
          "level-info": "var(--color-level-info)",
          "level-warning": "var(--color-level-warning)",
          "level-error": "var(--color-level-error)",
        },
      },
    },
  },
  plugins: [],
};

// eslint-disable-next-line no-undef
module.exports = config;
